export const FULL_DAY_WORK_HOURS = 8;

export const HALF_DAY_WORK_HOURS = 4;

export const LUNCH_HOURS = 1;
export const LUNCH_MAX_IDEAL_MINUTES = LUNCH_HOURS * 60;
export const LUNCH_MIN_IDEAL_MINUTES = 40;

export const ATTENDANCE_RATE_MAX_THRESHOLD_PERCENT = 90;
export const ATTENDANCE_RATE_MIN_THRESHOLD_PERCENT = 95;

export const CLOCK_IN_VARIATION_MAX_MINUTES = 45;
export const CLOCK_IN_VARIATION_MIN_MINUTES = 15;
